# docker-compose.yml
version: '3.8'

services:
  api-whatsapp-typescript-mvc:
    build: .
    container_name: api-whatsapp-typescript-mvc
    restart: unless-stopped
    ports:
      - "5001:3000"
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    volumes:
      - /home/ats/docker/api-whatsapp:/app/.wwebjs_auth
    networks:
      - pgvector_default
    mem_limit: 1g
    shm_size: 1g
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  pgvector_default:
    external: true